# .readthedocs.yaml - Read the Docs configuration file.
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details.

version: 2

build:
    os: ubuntu-22.04
    tools:
        python: "3.11"
    jobs:
        post_checkout:
            # Retrieve some git history, which will hopefully include the last release tag
            # and enable us to generate better version numbers.
            - git fetch --depth=256
    apt_packages:
        - build-essential
        - pkg-config
        - libfuse3-dev

python:
    install:
        - method: pip
          path: .

sphinx:
    configuration: rst/conf.py
