#!/bin/bash

R=$1

if [ "$R" = "" ]; then
    echo "Usage: upload-pypi 1.2.3 [test]"
    exit
fi

if [ "$2" = "test" ]; then
    export TWINE_REPOSITORY=testpyfuse3
else
    export TWINE_REPOSITORY=pyfuse3
fi

D=dist/pyfuse3-$R.tar.gz

twine upload $D
